### ISSUE TITLE
Failed to load xontrib jedi: module `xonsh.completers` has no attribute `base`

### ISSUE THREAD

**Issue by TeddyHuang-00** [xonsh/xontrib-jedi#3]
- Description: This is a regression. I cannot remember clearly which update between Python, xonsh and jedi broke the loading of xontrib jedi. It raises `AttributeError: module 'xonsh.completers' has no attribute 'base'` then ends loading: `Failed to load xontrib jedi.`
- environment:
  - System: macOS, archlinux, ubuntu
  - Python: 3.11.5
  - Xonsh: 0.14.1
  - Xontrib-jedi: 0.0.2
  - jedi: 0.19.0
- Traceback:
  ```log
  Traceback (most recent call last):
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 229, in xontribs_load
      update_context(name, ctx=ctx, full_module=full_module)
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 174, in update_context
      modctx = xontrib_context(name, full_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 140, in xontrib_context
      module = importlib.import_module(spec.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/imphooks.py", line 302, in exec_module
      rtn = self.loader.exec_module(module)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xontrib/jedi.py", line 163, in <module>
      xonsh.completers.base.complete_python = complete_jedi
      ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'xonsh.completers' has no attribute 'base'
  Traceback (most recent call last):
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 229, in xontribs_load
      update_context(name, ctx=ctx, full_module=full_module)
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 174, in update_context
      modctx = xontrib_context(name, full_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 140, in xontrib_context
      module = importlib.import_module(spec.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/imphooks.py", line 302, in exec_module
      rtn = self.loader.exec_module(module)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xontrib/jedi.py", line 163, in <module>
      xonsh.completers.base.complete_python = complete_jedi
      ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'xonsh.completers' has no attribute 'base'
  Traceback (most recent call last):
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 229, in xontribs_load
      update_context(name, ctx=ctx, full_module=full_module)
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 174, in update_context
      modctx = xontrib_context(name, full_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 140, in xontrib_context
      module = importlib.import_module(spec.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/imphooks.py", line 302, in exec_module
      rtn = self.loader.exec_module(module)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xontrib/jedi.py", line 163, in <module>
      xonsh.completers.base.complete_python = complete_jedi
      ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'xonsh.completers' has no attribute 'base'
  Traceback (most recent call last):
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 229, in xontribs_load
      update_context(name, ctx=ctx, full_module=full_module)
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 174, in update_context
      modctx = xontrib_context(name, full_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 140, in xontrib_context
      module = importlib.import_module(spec.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/imphooks.py", line 302, in exec_module
      rtn = self.loader.exec_module(module)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xontrib/jedi.py", line 163, in <module>
      xonsh.completers.base.complete_python = complete_jedi
      ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'xonsh.completers' has no attribute 'base'
  Traceback (most recent call last):
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 229, in xontribs_load
      update_context(name, ctx=ctx, full_module=full_module)
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 174, in update_context
      modctx = xontrib_context(name, full_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 140, in xontrib_context
      module = importlib.import_module(spec.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/imphooks.py", line 302, in exec_module
      rtn = self.loader.exec_module(module)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xontrib/jedi.py", line 163, in <module>
      xonsh.completers.base.complete_python = complete_jedi
      ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'xonsh.completers' has no attribute 'base'
  Traceback (most recent call last):
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 229, in xontribs_load
      update_context(name, ctx=ctx, full_module=full_module)
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 174, in update_context
      modctx = xontrib_context(name, full_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/xontribs.py", line 140, in xontrib_context
      module = importlib.import_module(spec.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/imphooks.py", line 302, in exec_module
      rtn = self.loader.exec_module(module)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/teddyhuang/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xontrib/jedi.py", line 163, in <module>
      xonsh.completers.base.complete_python = complete_jedi
      ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'xonsh.completers' has no attribute 'base'
  ```

**Comment by TeddyHuang-00** [comment]
I add another line in `site-packages/xontrib/jedi.py`:

```py
import xonsh.conpleters.base
```

This will definitely get rid of the warning, but I still don't know what to expect. My best guess is that since the monkey-patch works with `import xonsh`, importing a submodule and replacing that completion method should also work. Don't know if there's any way to verify this.
