### ISSUE TITLE
AttributeError: module 'xonsh.completers' has no attribute 'base'

### ISSUE THREAD

**Issue by anki-code** [xonsh/xontrib-jedi#5]
```xsh
xonsh --no-rc
$XONSH_SHOW_TRACEBACK = True
xpip install xontrib-jedi  # xontrib-jedi-0.0.2
xontrib load jedi
```
```xsh
Traceback (most recent call last):
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/xontribs.py", line 246, in xontribs_load
    update_context(name, ctx=ctx, full_module=full_module)
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/xontribs.py", line 191, in update_context
    modctx = xontrib_context(name, full_module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/xontribs.py", line 157, in xontrib_context
    module = importlib.import_module(spec.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xontrib/jedi.py", line 163, in <module>
    xonsh.completers.base.complete_python = complete_jedi
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'xonsh.completers' has no attribute 'base'
Failed to load xontrib jedi.
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by greg-hellings** [comment]
I am seeing this same error, as well.

**Comment by jnoortheen** [comment]
I don't think we need the monkeypatching of old Python completer. lets remove that line.

**Comment by greg-hellings** [comment]
New release works like a charm
